version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: crowley/testing-123
    parallelism: 20
    steps:
      - run:
          name: Starting Random Wait
          command: echo "Starting Random Wait......."
      - run:
          name: Starting Random Wait
          command: sleep $((RANDOM % 120))
      - run:
          name: "Runner Time :)"
          command: echo "I am on a runner!!!!!"